### ISSUE TITLE
Barbell tries to upgrade twice

### ISSUE THREAD

**Issue by iTitus** [mikemayhemdev/EvilWithin#310]
https://github.com/mikemayhemdev/EvilWithin/blob/a4ca79285af57d6002ceaf6d143f0f03ec9ba9d6/src/main/java/champ/relics/Barbells.java#L42-L51

**Comment by Mwallx** [comment]
easy fix

**Comment by Mwallx** [comment]
I mean this was fixed long ago too thanks.

**Comment by iTitus** [comment]
nice
