### ISSUE TITLE
Cable Spool doesn't "copy" the card, instead creates a new instance

### ISSUE THREAD

**Issue by iTitus** [mikemayhemdev/EvilWithin#311]
Maybe use `makeStatEquivalentCopy()` so that it copies the upgrade status as well?

https://github.com/mikemayhemdev/EvilWithin/blob/a4ca79285af57d6002ceaf6d143f0f03ec9ba9d6/src/main/java/automaton/relics/CableSpool.java#L37-L45

**Comment by Mwallx** [comment]
applied

**Comment by iTitus** [comment]
Noted
